import { ColDef, ColGroupDef } from "ag-grid-community";

export interface IKpiProgressSummaryData {
  country: string;
  tocPillar: string;
  kpi: string;
  aggregationLevel: string;
  baselineYear0: string;
  year1Actual: string;
  year1Target: string;
  year3Target: string;
  year5Target: string;
}

export function getDummyKpiProgressSummaryData(): IKpiProgressSummaryData[] {
  return [
    {
      country: "Total (all LMH countries)",
      tocPillar: "Cross-Cutting",
      kpi: "Number of community and frontline health workers supported by Last Mile Health and its government partners to provide quality community-based primary healthcare services ",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "8869",
      year1Actual: "9400",
      year1Target: "9418",
      year3Target: "10860",
      year5Target: "11460",
    },
    {
      country: "Total (all LMH countries)",
      tocPillar: "Cross-Cutting",
      kpi: "Number of community and frontline health workers supported by Last Mile Health and its government partners to provide quality community-based primary healthcare services ",
      aggregationLevel: "Cumulative (all time)",
      baselineYear0: "12149",
      year1Actual: "14511",
      year1Target: "",
      year3Target: "",
      year5Target: "",
    },
    {
      country: "Total (all LMH countries)",
      tocPillar: "Cross-Cutting",
      kpi: "Population of the communities with improved access to quality, community-based primary healthcare through Last Mile Health and its government partners",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "8668558",
      year1Actual: "8401645",
      year1Target: "8761482",
      year3Target: "10443983",
      year5Target: "21120181",
    },
    {
      country: "Total (all LMH countries)",
      tocPillar: "Cross-Cutting",
      kpi: "Population of the communities with improved access to quality, community-based primary healthcare through Last Mile Health and its government partners",
      aggregationLevel: "Cumulative (all time)",
      baselineYear0: "12178826",
      year1Actual: "16119588",
      year1Target: "",
      year3Target: "",
      year5Target: "",
    },
    {
      country: "Ethiopia",
      tocPillar: "Cross-Cutting",
      kpi: "Number of community and frontline health workers supported by Last Mile Health and its government partners to provide quality community-based primary healthcare services ",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "2024",
      year1Actual: "1699",
      year1Target: "1958",
      year3Target: "2250",
      year5Target: "2250",
    },
    {
      country: "Ethiopia",
      tocPillar: "Cross-Cutting",
      kpi: "Number of community and frontline health workers supported by Last Mile Health and its government partners to provide quality community-based primary healthcare services ",
      aggregationLevel: "Cumulative (all time)",
      baselineYear0: "4223",
      year1Actual: "5636",
      year1Target: "5692",
      year3Target: "79425",
      year5Target: "10192",
    },
    {
      country: "Ethiopia",
      tocPillar: "Cross-Cutting",
      kpi: "Population of the communities with improved access to quality, community-based primary healthcare through Last Mile Health and its government partners",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "4757500",
      year1Actual: "3835000",
      year1Target: "4405500",
      year3Target: "5062500",
      year5Target: "5062500",
    },
    {
      country: "Ethiopia",
      tocPillar: "Cross-Cutting",
      kpi: "Population of the communities with improved access to quality, community-based primary healthcare through Last Mile Health and its government partners",
      aggregationLevel: "Cumulative (all time)",
      baselineYear0: "7691056",
      year1Actual: "10801056",
      year1Target: "10995181",
      year3Target: "16057681",
      year5Target: "21120181",
    },
    {
      country: "Ethiopia",
      tocPillar: "Strengthen",
      kpi: "Ethiopia MOH institutionalizes LMH's blended learning approach for HEW integrated refresher training",
      aggregationLevel: "Cumulative (all time)",
      baselineYear0:
        "RMNCH adapted and piloted in FY22; scaled up for broader use in FY23 using learning from pilot.  Learner reports used for supervision. NCD and MCD adapted in FY23.",
      year1Actual:
        "43% of IRT modules currently adapted. RMNCH: continued scale-up. NCD & MCD: scale-up began in Q3. SBCC, Hygiene & Env Health, and First Aid: adaptation underway. ",
      year1Target:
        "80% of the Integrated Refresher Training (IRT) content for HEWs has been adapted to utilize the blended approach for HEW training.",
      year3Target:
        "100% of the Integrated Refresher Training (IRT) content for HEWs has been adapted to utilize the blended approach for HEW training.",
      year5Target:
        "IRT for HEWs using blended learning is being actively implemented by other training stakeholders and MOH.",
    },
    {
      country: "Ethiopia",
      tocPillar: "Upskill",
      kpi: "Number of community and frontline health workers who have completed a full blended learning training module",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "",
      year1Actual: "",
      year1Target: "",
      year3Target: "",
      year5Target: "",
    },
    {
      country: "Ethiopia",
      tocPillar: "Upskill",
      kpi: "Number of community and frontline health workers who have completed a full blended learning training module",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "1904",
      year1Actual: "1523",
      year1Target: "1958",
      year3Target: "2250",
      year5Target: "2250",
    },
    {
      country: "Ethiopia",
      tocPillar: "Upskill",
      kpi: "Number of community and frontline health workers who have completed a full blended learning training module",
      aggregationLevel: "Cumulative (all time)",
      baselineYear0: "3011",
      year1Actual: "4251",
      year1Target: "",
      year3Target: "",
      year5Target: "",
    },
    {
      country: "Ethiopia",
      tocPillar: "Upskill",
      kpi: "Total number of blended training module completions by community and frontline health workers",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "1904",
      year1Actual: "2125",
      year1Target: "3916",
      year3Target: "4500",
      year5Target: "300",
    },
    {
      country: "Ethiopia",
      tocPillar: "Upskill",
      kpi: "Total number of blended training module completions by community and frontline health workers",
      aggregationLevel: "Cumulative (all time)",
      baselineYear0: "3013",
      year1Actual: "5138",
      year1Target: "",
      year3Target: "",
      year5Target: "",
    },
    {
      country: "Ethiopia",
      tocPillar: "Upskill",
      kpi: "Percentage of HEWs and HEW Supervisors who have received a passing score in a post-training knowledge assessment",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "88%",
      year1Actual: "93%",
      year1Target: "75%",
      year3Target: "75%",
      year5Target: "75%",
    },
    {
      country: "Ethiopia",
      tocPillar: "Upskill",
      kpi: "Percentage of HEWs and HEW Supervisors who have received a passing score in a post-training skills assessment",
      aggregationLevel: "Annual (FY)",
      baselineYear0: "88%",
      year1Actual: "93%",
      year1Target: "75%",
      year3Target: "75%",
      year5Target: "75%",
    },
    // {
    //   country: "",
    //   tocPillar: "",
    //   kpi: "",
    //   aggregationLevel: "",
    //   baselineYear0: "",
    //   year1Actual: "",
    //   year1Target: "",
    //   year3Target: "",
    //   year5Target: "",
    // },
    {
      country: "Liberia",
      tocPillar: "Upskill",
      kpi: "Increase in literacy rate",
      aggregationLevel: "National",
      baselineYear0: "2020",
      year1Actual: "65%",
      year1Target: "70%",
      year3Target: "80%",
      year5Target: "90%",
    },
  ];
}
