"use client";
import React, { memo, useCallback } from "react";
import DataTable from "@/components/shared/programData/agGridTable/data-table";

// Import all program schemas
import LibCbisColumns, { ILibCbis } from "./program-schema/lib_cbis";
import LibChwMasterListColumns, {
  ILibChwMasterList,
} from "./program-schema/lib_chw_master_list";
import {
  createProgramConfig,
  FilterButton,
  NoDataView,
  ProgramRegistry,
} from "@/components/shared/programData/agGridTable/table-helpers";

// import {
//   AdvancedTableExample,
//   BasicTableExample,
//   DynamicAPITableExample,
// } from "@/components/tables/tanstack/example";
// import {
//   AdvancedFiltersExample,
//   CompleteExample,
//   CustomHeightsExample,
//   GroupingExample,
//   StripedExample,
//   VerticalHeadersExample,
// } from "@/components/tables/tanstack/example2";
// import { AutoGenerateDynamicExample } from "@/components/tables/tanstack/example3";
// import {
//   AllFeaturesExample,
//   MergedCellsExample,
// } from "@/components/tables/tanstack/example4";
// import DynamicApiTable from "@/components/tables/tanstack/dyanamicApiTable";
import DynamicApiDataTable from "@/components/tables/ag-grid/DynamicApiDataTable";

// Program Registry - Add new programs here
const PROGRAM_REGISTRY: ProgramRegistry = {
  lib_cbis: createProgramConfig<ILibCbis>(
    "liberia",
    "lib_cbis",
    LibCbisColumns
  ),
  lib_chw_master_list: createProgramConfig<ILibChwMasterList>(
    "liberia",
    "lib_chw_master_list",
    LibChwMasterListColumns
  ),
};

// Export available program codes for type safety
type ProgramCode = keyof typeof PROGRAM_REGISTRY;

interface Props {
  programCode: string;
}

const LiberiaTableComponent = ({ programCode }: Props) => {
  const [showToolBar, setShowToolBar] = React.useState(false);

  const toggleToolBar = useCallback(() => {
    setShowToolBar((prev) => !prev);
  }, []);

  const config = PROGRAM_REGISTRY[programCode as ProgramCode];

  // if (!config) {
  //   return <NoDataView programCode={programCode} />;
  // }

  console.log("LiberiaTableComponent render - programCode:", programCode);

  return (
    <>
      <div className="absolute -top-[40px] right-[2px] z-100 border-none border-red-500">
        <FilterButton showToolBar={showToolBar} onClick={toggleToolBar} />
      </div>
      {/* <DataTable
        columns={config.columns}
        data={null}
        showToolBar={showToolBar}
        apiURL={config.apiURL}
        onDataChange={(dd) => console.log("hey there", dd)}
        pageSize={500}
      /> */}

      <DynamicApiDataTable
        apiConfig={{
          // apiUrl: config.apiURL, // `liberia/lib_cbis`
          apiUrl: `liberia/${programCode}`,
          perPage: 500,
          pageSizeOptions: [100, 500, 1000, 5000],
        }}
        columnConfig={{
          // columns: config.columns,
          autoGenerateColumns: true,
          namingStrategy: "mapped",
          enableColumnMenu: true,
          enableFilters: true,

          enableSorting: true,
          enableFloatingFilter: true,
          columnNameMap: {
            "1_2b_births_home_chss": "Births at Home CHSS",
            "1_2c_births_health_facility": [
              "Births at Health Facility",
              "number",
            ],
          },
        }}
        enableRowSelection={true}
        showToolBar={showToolBar}

        // onRowSelectionChange={(rows) => console.log("selected rows", rows)}
        // onDataChange={(data) => {
        //   console.log("data", data);
        // }}
      />

      {/* <div className="border h-full"> */}
      {/* <AdvancedTableExample /> */}
      {/* <CustomHeightsExample /> */}
      {/* <CompleteExample /> */}
      {/* <AllFeaturesExample /> */}

      {/* <DynamicApiTable
          apiParams={{
            apiUrl:
              "https://p8wutvgugr.us-east-1.awsapprunner.com/api/program_data/liberia/lib_cbis",
            // page: 1,
            perPage: 1000,
          }}
          showAdvancedFilter
          showColumnMenu
          onExport={() => {}}
          showVerticalLines
          headerHeight={"20px"}
        /> */}
      {/* </div> */}
    </>
  );
};

export default memo(LiberiaTableComponent);
